pub const LINE_SIZE: usize         = 128;
pub const BLOCK_SIZE: usize        = 1024 * 32;
pub const TOTAL_LINES: usize       = BLOCK_SIZE / LINE_SIZE;
pub const MARK_LINES: usize        = ((TOTAL_LINES - 1) / LINE_SIZE) + 1;
pub const EFFECTIVE_LINES: usize   = TOTAL_LINES - MARK_LINES;
pub const BLOCK_CAPACITY: usize    = EFFECTIVE_LINES * LINE_SIZE;
pub const META_OFFSET: usize       = BLOCK_CAPACITY;
pub const BLOCK_MARK_OFFSET: usize = BLOCK_CAPACITY + EFFECTIVE_LINES;
pub const SPACE_SIZE: usize = BLOCK_SIZE * 1024 * 20; // ~0.6Gib
pub const BLOCKS_PER_SPACE: usize = SPACE_SIZE / BLOCK_SIZE;
